security:
  ignored: /**

server:
  port: 8952

---
server:
  port: ${PORT}

spring:
  profiles: production
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
discord:
  token: $(PROD_DISCORD_TOKEN)

---
server:
  port: ${PORT}

spring:
  profiles: dev
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
discord:
  token: $(DEV_DISCORD_TOKEN)

---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/CookieBot
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
discord:
  token:
