spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CookieBot
    username: postgres
    password: 2DoRblt2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
security:
  ignored: /**
discord:
  token: NTQ0ODg5OTcyMDA0NzQ5MzEy.D0Sc0g.19n9etb7Dhq_1HtHZjcnPJ-kYsY