spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CookieBot
    username: postgres
    password: ENC(gHy95v4Yegc+Yz+m1ug8SHO/trY+DFc2)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
security:
  ignored: /**
discord:
  token: ENC(VR8XwS7weKlju0zR6NVeKtWkoWhOWp55ZhLHEaujpmBwgwQxtb5T9aKl1C+LVbTlzUWZ9SdAulzHseJmZCPrmRR60mOtlqER)
logging:
  level:
    org.springframework.web: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"