security:
  ignored: /**

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
app:
  version: 2.0
---
server:
  port: ${PORT}
spring:
  profiles: production
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
discord:
  token: ${PROD_DISCORD_TOKEN}
  bot-channel-id: 544942649036242964
okta:
  oauth2:
    issuer: ${OAUTH_ISSUER}
    client-id: ${OAUTH_CLIENT_ID}
    client-secret: ${OAUTH_CLIENT_SECRET}
    roles-claim: groups

---
server:
  port: ${PORT}
spring:
  profiles: dev
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
discord:
  token: ${DEV_DISCORD_TOKEN}
  bot-channel-id: 589975110090489907
okta:
  oauth2:
    issuer: ${OAUTH_ISSUER}
    client-id: ${OAUTH_CLIENT_ID}
    client-secret: ${OAUTH_CLIENT_SECRET}
    roles-claim: groups

